language: java
jdk: oraclejdk8
dist: trusty

script: mvn -B verify -Dsauce.user=$SAUCE_USER -Dsauce.sauceAccessKey=$SAUCE_ACCESSKEY -Dvaadin.proKey=$VAADIN_PRO_KEY -Dvaadin.productionMode -Dcom.vaadin.testbench.Parameters.testsInParallel=2

branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/vaadin-cookie-consent-flow

